---
# tasks file for flask_role
- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: docker-compose.yml

- name: Copy changer script
  copy:
    src: changer.sh
    dest: changer.sh
    mode: +x

- name: Copy .env file
  copy: 
    src: .env
    dest: .env

- name: Make changes
  shell: bash changer.sh
  ignore_errors: yes

- name: Docker stop
  shell: docker-compose stop {{ registry_admin }}    

- name: Make deploy
  shell: docker-compose up -d {{ registry_admin }}

#- name: Remove docker-compose.yml
#  file: path=docker-compose.yml state=absent
...
